// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace study_center_ef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("study_center_ef.Entities.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<byte>("Capacity")
                        .HasColumnType("TINYINT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("ClassID");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            Capacity = (byte)30,
                            ClassName = "Math-101",
                            Description = "Intro to Algebra"
                        },
                        new
                        {
                            ClassID = 2,
                            Capacity = (byte)25,
                            ClassName = "Sci-102",
                            Description = "Basic Chemistry"
                        },
                        new
                        {
                            ClassID = 3,
                            Capacity = (byte)20,
                            ClassName = "Eng-201",
                            Description = "Advanced Grammar"
                        },
                        new
                        {
                            ClassID = 4,
                            Capacity = (byte)15,
                            ClassName = "Hist-301",
                            Description = "World History"
                        });
                });

            modelBuilder.Entity("study_center_ef.Entities.GradeLevel", b =>
                {
                    b.Property<int>("GradeLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeLevelID"));

                    b.Property<string>("GradeLevelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("GradeLevelID");

                    b.ToTable("GradeLevels", (string)null);

                    b.HasData(
                        new
                        {
                            GradeLevelID = 1,
                            GradeLevelName = "6th Grade"
                        },
                        new
                        {
                            GradeLevelID = 2,
                            GradeLevelName = "7th Grade"
                        },
                        new
                        {
                            GradeLevelID = 3,
                            GradeLevelName = "8th Grade"
                        },
                        new
                        {
                            GradeLevelID = 4,
                            GradeLevelName = "9th Grade"
                        });
                });

            modelBuilder.Entity("study_center_ef.Entities.GradeLevelSubject", b =>
                {
                    b.Property<int>("GradeLevelSubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeLevelSubjectID"));

                    b.Property<int>("Fees")
                        .HasColumnType("int");

                    b.Property<int>("GradeLevelID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("GradeLevelSubjectID");

                    b.HasIndex("GradeLevelID");

                    b.HasIndex("SubjectID");

                    b.ToTable("GradeLevelSubjects", (string)null);
                });

            modelBuilder.Entity("study_center_ef.Entities.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DateTime");

                    b.Property<int>("GradeLevelSubjectID")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("GroupStudentCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GroupID");

                    b.HasIndex("ClassID");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("study_center_ef.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DateTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<byte>("Gender")
                        .HasColumnType("TINYINT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("PersonID");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("study_center_ef.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DateTime");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("study_center_ef.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            SubjectID = 1,
                            SubjectName = "Mathematics"
                        },
                        new
                        {
                            SubjectID = 2,
                            SubjectName = "Science"
                        },
                        new
                        {
                            SubjectID = 3,
                            SubjectName = "English"
                        },
                        new
                        {
                            SubjectID = 4,
                            SubjectName = "History"
                        },
                        new
                        {
                            SubjectID = 5,
                            SubjectName = "Geography"
                        });
                });

            modelBuilder.Entity("study_center_ef.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("DateTime");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal");

                    b.HasKey("TeacherID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("study_center_ef.Entities.GradeLevelSubject", b =>
                {
                    b.HasOne("study_center_ef.Entities.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("study_center_ef.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeLevel");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("study_center_ef.Entities.Group", b =>
                {
                    b.HasOne("study_center_ef.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("study_center_ef.Entities.Student", b =>
                {
                    b.HasOne("study_center_ef.Entities.Person", "Person")
                        .WithOne("Student")
                        .HasForeignKey("study_center_ef.Entities.Student", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("study_center_ef.Entities.Teacher", b =>
                {
                    b.HasOne("study_center_ef.Entities.Person", "Person")
                        .WithOne("Teacher")
                        .HasForeignKey("study_center_ef.Entities.Teacher", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("study_center_ef.Entities.Person", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("Teacher")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
